# Generated by Django 4.2.18 on 2025-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_savingsoption_customer_savings_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsoption',
            name='name',
        ),
        migrations.AddField(
            model_name='savingsoption',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
