# Generated by Django 4.2.18 on 2025-06-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_remove_savingsoption_name_savingsoption_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='next_of_kin_phone',
        ),
    ]
